### ISSUE TITLE
Failed to create Mujoco runtime on MAC M1

### ISSUE THREAD

**Issue by DinoDany** [Balint-H/mj-unity-tutorial#1]
Hello!

Thank you so much for creating this tutorial! I have some trouble running the mujoco scene. I imported the json from the package manager and I copied the lib on the assets folder renamed as mujoco.dylib but I still have this problem, which is odd because I have run mujoco-unity applications outside this tutorial. Any help would be appreciated. Thank you so much :) 

![image](https://user-images.githubusercontent.com/93410674/208625385-0bc9cc46-1db3-4d9e-b331-079755a9f61e.png)

**Comment by Balint-H** [comment]
Hello!

I've been interested in learning how to run mujoco-unity on other systems so this is perfect. Have you removed the old dll? Also is the mac library you have versioned 2.3.1? What is the full exception message you get?

I hope we can figure this out, then the instructions can be updated based on that.

**Comment by Balint-H** [comment]
Also, you may need to restart the editor when changing dynamic libraries, as once they are loaded they are not unloaded (Although this may not be the case if the library fails to load, which is what I suspect might be happening here)

**Comment by DinoDany** [comment]
That's great! ... So I have been restarting the editor after every change. It is not working): I think the library is loading because it is recognizing the Mujoco elements, but is having problems creating the scene. It is throwing this exception:

![image](https://user-images.githubusercontent.com/93410674/208636266-9d2894a6-ea6a-4bc0-9b27-9156b101d557.png)

So I think is is a problem generating the MjModel/MjData. This is the first error:

![image](https://user-images.githubusercontent.com/93410674/208636620-21aebc81-b9f7-4210-9fcf-adde5f8d4bbd.png)

I pulled the last version of MuJoco before importing the json and I got the library from mujoco 2.3.1

**Comment by Balint-H** [comment]
In the MjGlobalSettings component, you can designate a filename that will be used to save the generated XML that is supplied to the mujoco instance. If this is an XML generation error then examining that file may be helpful. The path to the generated file should be printed out on the console after trying to start play mode.

**Comment by DinoDany** [comment]
Hmm,  Ok. Found it. it is very different to the original cartpole xml file 
[test1.xml.zip](https://github.com/Balint-H/mj-unity-tutorial/files/10267500/test1.xml.zip)

**Comment by DinoDany** [comment]
Do you know what number size should Memory be? In Mj Gobal Settings/Global Sizes / memory

![image](https://user-images.githubusercontent.com/93410674/208645531-59be1064-ed32-47db-8b65-8c6be00a1690.png)

When I change the values, the first error changes too from:

![image](https://user-images.githubusercontent.com/93410674/208645710-4815c545-5227-4070-8fd1-fe81495fe607.png)
  to 
![image](https://user-images.githubusercontent.com/93410674/208646135-804c8f4e-35fa-48f1-b306-992754872f9b.png)

**Comment by DinoDany** [comment]
Well, there are not more errors with size 1000...

**Comment by Balint-H** [comment]
I expected that in the later versions of MuJoCo the sizes would be automatically calculated, but maybe this is not the case yet for the mac version. However, the range of 1000 or maybe even less used to be good enough for most scenes. Thanks for finding this, I'll update the sizes for the next push of the library for the future!

**Comment by DinoDany** [comment]
Great! I'm happy we were able to figure it out! :)
