### ISSUE TITLE
[Minor] Null Pointer?

### ISSUE THREAD

**Issue by Engineering-Geek** [Balint-H/mj-unity-tutorial#6]
Issue: Switching to next page for a tutorial is a little bugged.

Target tutorial of paragraph 'Switch Tutorial' of the page '15-LastPage' is null. Did you forget to specify to which tutorial the user should transition to?
UnityEngine.Debug:LogError (object)
Unity.Tutorials.Core.Editor.TutorialView:SetupParagraphUI (UnityEngine.UIElements.VisualElement,Unity.Tutorials.Core.Editor.TutorialParagraph,string) (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Views/TutorialView.cs:280)
Unity.Tutorials.Core.Editor.TutorialView:ShowCurrentTutorialContent () (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Views/TutorialView.cs:350)
Unity.Tutorials.Core.Editor.TutorialView:Refresh () (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Views/TutorialView.cs:120)
Unity.Tutorials.Core.Editor.TutorialController:OnPageInitiated (Unity.Tutorials.Core.Editor.Tutorial,Unity.Tutorials.Core.Editor.TutorialPage,int) (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Controllers/TutorialController.cs:304)
UnityEngine.Events.UnityEvent`3<Unity.Tutorials.Core.Editor.Tutorial, Unity.Tutorials.Core.Editor.TutorialPage, int>:Invoke (Unity.Tutorials.Core.Editor.Tutorial,Unity.Tutorials.Core.Editor.TutorialPage,int)
Unity.Tutorials.Core.Editor.Tutorial:RaisePageInitiated (Unity.Tutorials.Core.Editor.TutorialPage,int) (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Core/Tutorial.cs:524)
Unity.Tutorials.Core.Editor.Tutorial:TryGoToNextPage () (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Core/Tutorial.cs:429)
Unity.Tutorials.Core.Editor.TutorialController:LoadNextTutorialPage () (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Controllers/TutorialController.cs:378)
Unity.Tutorials.Core.Editor.TutorialController:OnTutorialNavigationRequested (Unity.Tutorials.Core.Editor.TutorialNavigationEvent) (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Controllers/TutorialController.cs:140)
Unity.Tutorials.Core.Editor.EventManager/<>c__DisplayClass2_0`1<Unity.Tutorials.Core.Editor.TutorialNavigationEvent>:<AddListener>b__0 (Unity.Tutorials.Core.Editor.AppEvent) (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Core/Events.cs:68)
Unity.Tutorials.Core.Editor.EventManager:Broadcast (Unity.Tutorials.Core.Editor.AppEvent) (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Core/Events.cs:100)
Unity.Tutorials.Core.Editor.TutorialWindow:Broadcast (Unity.Tutorials.Core.Editor.AppEvent) (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Core/TutorialWindow.cs:544)
Unity.Tutorials.Core.Editor.TutorialView:OnNextButtonClicked () (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Views/TutorialView.cs:383)
Unity.Tutorials.Core.Editor.UIElementsUtils/<>c__DisplayClass2_0:<SetupButton>b__0 () (at ./Library/PackageCache/com.unity.learn.iet-framework@3.1.3/Editor/Utils/UIElementsUtils.cs:29)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&) (at /home/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:219)

**Comment by Balint-H** [comment]
Hi, this was just an issue that cropped up due to missing transitions between Tutorials. It should be fixed now for the existing tutorials, but I'll keep an eye out if it appears again.
